### ISSUE TITLE
The hgetall of reids can be replaced by hscan

### ISSUE THREAD

**Issue by ab0029** [tarreislam/laravel-redis-scout-engine#3]
Tarre\RedisScoutEngine\Services\RedisSearchService
```php
    /**
     * @param $fqdn
     * @return array
     */
    protected function hGetAll($fqdn)
    {
        return $this->redisInstance->hGetAll($fqdn);
    }
```
change the code to：
```php
    /**
     * @param $fqdn
     * @return array
     */
    protected function hscan($fqdn)
    {
        return function() use ($fqdn) {
            $iterator = null;

            while (true) {
                $result = $this->redisInstance->hscan($fqdn, $iterator, [
                    'count' => 1000,
                ]);

                if ( $result === false ) {
                    break;
                }

                $iterator = $result[0];

                foreach ($result[1] as $key => $value) {
                    yield $key => $value;
                }
            }
        };
    }
```

**Comment by tarreislam** [comment]
Thanks for the input.  Do you mind submitting a PR, if not I can do the changes and tests manually ofc :)

**Comment by ab0029** [comment]
you can do it 😄

**Comment by ab0029** [comment]
However, after my test, I felt that the performance was not good enough, and I tested 30K data, and the response took about 3 seconds

**Comment by tarreislam** [comment]
I see,

However when I wrote this, I did it with 0 research, so there is probably stuff that could be improved, like using iterators and chunking here and there

**Comment by ab0029** [comment]
Using hgetall to search for 30k data also takes 3 seconds, while hsacn is designed to reduce memory usage

**Comment by ab0029** [comment]
It is easy to report an error of `out of memory` when using hgetall

**Comment by tarreislam** [comment]
Thanks, ill make the update asap
